export const ACTIVITY_LOCATION_SET = "ACTIVITY_LOCATION_SET";
export const USER_CLICK_RECORD_MOOSE = "USER_CLICK_RECORD_MOOSE";
export const USER_CLICK_ADD_MOOSE = "USER_CLICK_ADD_MOOSE";
export const ACTIVITY_UPDATE_MOOSE = "ACTIVITY_UPDATE_MOOSE";
export const GET_GEOLOCATION = 'GET_GEOLOCATION';
export const USER_CLICK_RECORD_GENDER = 'USER_CLICK_RECORD_GENDER';
export const ACTIVITY_DELETE_MOOSE = "ACTIVITY_DELETE_MOOSE";
