export const ACTIVITY_LOCATION_SET = "ACTIVITY_LOCATION_SET";
export const USER_CLICK_RECORD_MOOSE = "USER_CLICK_RECORD_MOOSE";
export const USER_CLICK_ADD_MOOSE = "USER_CLICK_ADD_MOOSE";
export const ACTIVITY_UPDATE_MOOSE_AGE = "ACTIVITY_UPDATE_MOOSE_AGE";
